name: docker-buildx

on:
  watch:
    types: [started]
  push:
    branches:
      - 'master'

env:
  DOCKERHUB_USER: wiserain
  DOCKERHUB_REPO: aria2

jobs:
  docker-buildx:
    runs-on: ubuntu-20.04
    if: (github.event_name != 'watch') || (github.actor == github.event.repository.owner.login)
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Initial Buildx
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}:testing
          platform: linux/amd64,linux/arm/v7,linux/arm64
      - 
        name: Load Built Image and Get Variables
        id: vars
        run: |
          docker buildx build \
            -t ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}:testing \
            --platform=linux/amd64 \
            --load \
            .
          CID=$(docker run -d ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}:testing)
          VER=$(echo $(docker exec $CID aria2c -v) | awk '{print $3}')
          docker rm -f $CID
          echo ::set-output name=app_ver::${VER}
          echo ::set-output name=github_desc::$(curl -sX GET https://api.github.com/repos/${GITHUB_REPOSITORY} | jq -r .description)
          echo ::set-output name=github_branch::${GITHUB_REF#refs/heads/}
      -
        name: Login to docker.io
        uses: docker/login-action@v1 
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Login to ghcr.io
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - 
        name: Buildx and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: |
            ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}:${{ steps.vars.outputs.app_ver }}
            ghcr.io/${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}:latest
            ghcr.io/${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}:${{ steps.vars.outputs.app_ver }}
          platform: linux/amd64,linux/arm/v7,linux/arm64
          push: true
      -
        name: Update Dockerhub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          repository: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
          short-description: ${{ steps.vars.outputs.github_desc }}
      -
        name: Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}:${{ steps.vars.outputs.app_ver }}
            ghcr.io/${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}:latest
            ghcr.io/${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}:${{ steps.vars.outputs.app_ver }}
